### ISSUE TITLE
Simpler IDs

### ISSUE THREAD

**Issue by Eepsquared** [SeanLatimer/I3DMappingExporter#3]
Can you make a checkbox option/switch to output only the shape name and not the whole heirarchy? So, instead of:
`<i3dMapping id="lizardFloodLightTrailer_telescopeElement1_telescopeElement2_telescopeElement3_telescopeElement4_telescopeElement5_telescopeElement6_telescopeElement7_telescopeElement8_colPart" node="0>5|0|0|0|0|0|0|0|1" />`

It would output the last ID only:
`<i3dMapping id="colPart" node="0>5|0|0|0|0|0|0|0|1" />`

I know this might give duplicate IDs but it's easier to add on less than to take off more.

Thanks.

**Comment by SeanLatimer** [comment]
I'll look at this after I finish up working on a better installer.

Although I won't be shipping this until I can guarantee that there won't be any ID collision.
